name: English147
pygments: true
permalink: none
baseurl: /English147
subtitle: T05 | Alex Christie

page3: Student Resources
page4: Office Hours

delay2: "-webkit-animation-delay: .2s; -moz-animation-delay: .2s; -ms-animation-delay: 
.2s; animation-delay: .2s;"
delay4: "-webkit-animation-delay: .4s; -moz-animation-delay: .4s; -ms-animation-delay: .4s; animation-delay: .4s;"
delay6: "-webkit-animation-delay: .6s; -moz-animation-delay: .6s; -ms-animation-delay: .6s; animation-delay: .6s;"
delay8: "-webkit-animation-delay: .8s; -moz-animation-delay: .8s; -ms-animation-delay: .8s; animation-delay: .8s;"